# Site settings
title: Thien Tran
description: Thien Tran

# User settings
username: Thien Tran
user_description: A personal website showcasing Thien Tran (Thien Long Tran), a Computer Science student at the University of New Orleans.

email: tltran5@uno.edu

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-slate
